import numpy as np
import matplotlib.pyplot as plt
from SignalGenerator import ModemSignalGenerator
from NoiseGenerator import ModemNoiseGenerator

class ModemAnomalyInjector:
    def __init__(self, signal):
        self.signal = signal

    def apply_clipping(self, threshold=0.8):
        return np.clip(self.signal, -threshold, threshold)

    def apply_echo(self, delay=3000, decay=0.5):
        delayed_sig = np.pad(self.signal, (delay, 0), 'constant')[:len(self.signal)]
        return self.signal + delayed_sig * decay

    def apply_dropout(self, duration_pct=0.2):
        mask = np.ones_like(self.signal)
        start = np.random.randint(0, len(self.signal) - int(len(self.signal)*duration_pct))
        end = start + int(len(self.signal)*duration_pct)
        mask[start:end] = 0.05 
        return self.signal * mask

if __name__ == "__main__":
    bits = np.random.randint(0, 2, 20)

    signal_generator = ModemSignalGenerator()
    clear_signal = signal_generator.GenerateFrame(bits)

    noise_generator = ModemNoiseGenerator(clear_signal, 10)
    noised_signal = noise_generator.GenerateNoise()

    anomaly_injector = ModemAnomalyInjector(noised_signal)
    anomalous_signal = anomaly_injector.apply_echo()

    plt.subplot(2,1,1)
    plt.plot(noised_signal[:17000])
    plt.title("Noised signal generated by modem")
    plt.xlabel("Bit")
    plt.ylabel("Amplitude")

    plt.subplot(2,1,2)
    plt.plot(anomalous_signal[:17000])
    plt.title("Signal with injected anomaly")
    plt.xlabel("Bit")
    plt.ylabel("Amplitude")
    plt.show()