import numpy as np
import matplotlib.pyplot as plt
from SignalGenerator import ModemSignalGenerator

class ModemNoiseGenerator:
    def __init__(self, signal, snr_db = 10):
        self.signal = signal
        self.snr_db = snr_db

    def GenerateNoise(self):
        signal_power = np.mean(self.signal ** 2)
        snr_linear = 10 ** (self.snr_db / 10)
        noise_power = signal_power / snr_linear
        noise = np.sqrt(noise_power) * np.random.randn(len(self.signal))
        return self.signal + noise

if __name__ == "__main__":
    bits = np.random.randint(0, 2, 20)

    signal_generator = ModemSignalGenerator()
    clear_signal = signal_generator.GenerateFrame(bits)

    noise_generator = ModemNoiseGenerator(clear_signal, 10)
    noised_signal = noise_generator.GenerateNoise()

    print("Generated signal length: ", len(clear_signal))
    plt.figure(figsize=(12,6))

    plt.subplot(2,1,1)
    plt.plot(clear_signal[1000:1100])
    plt.title("Signal generated by modem")
    plt.xlabel("Bit")
    plt.ylabel("Amplitude")

    plt.subplot(2,1,2)
    plt.plot(noised_signal[1000:1100])
    plt.title(f"Noise simulation by modem (SNR: {noise_generator.snr_db})")
    plt.xlabel("Bit")
    plt.ylabel("Amplitude")
    plt.show()