import numpy as np
import matplotlib.pyplot as plt

class ModemSignalGenerator:
    def __init__(self, fs = 44100, bit_dur = 0.02, f0 = 2000, f1 = 8000, amplitude = 1):
        self.fs = fs
        self.bit_dur = bit_dur
        self.f0 = f0
        self.f1 = f1
        self.amplitude = amplitude
        self.samples_per_bit = int(fs * bit_dur)

    def GenerateLfmBit(self, bit):
        t = np.linspace(0, self.bit_dur, self.samples_per_bit, endpoint=False)
        k = (self.f1 - self.f0) / self.bit_dur

        if bit == 0:
            phase = 2 * np.pi * (self.f0 * t + 0.5 * k * t ** 2)
        else:
            phase = 2 * np.pi * (self.f1 * t + 0.5 * k * t ** 2)

        return self.amplitude * np.cos(phase)

    def GenerateFrame(self, bit_sequence):
        frame = np.concatenate(
            [self.GenerateLfmBit(bit) for bit in bit_sequence]
        )
        return frame

if __name__ == "__main__":
    generator = ModemSignalGenerator()

    bits = np.random.randint(0, 2, 20)

    clear_signal = generator.GenerateFrame(bits)

    print("Generated signal length: ", len(clear_signal))

    plt.figure(figsize=(12,4))
    plt.plot(clear_signal[:4000])
    plt.title("Signal generated by modem")
    plt.xlabel("Bit")
    plt.ylabel("Amplitude")
    plt.show()